# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tfx.proto.orchestration import execution_watcher_pb2 as tfx_dot_proto_dot_orchestration_dot_execution__watcher__pb2


class ExecutionWatcherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateExecutionInfo = channel.unary_unary(
                '/tfx.orchestration.ExecutionWatcherService/UpdateExecutionInfo',
                request_serializer=tfx_dot_proto_dot_orchestration_dot_execution__watcher__pb2.UpdateExecutionInfoRequest.SerializeToString,
                response_deserializer=tfx_dot_proto_dot_orchestration_dot_execution__watcher__pb2.UpdateExecutionInfoResponse.FromString,
                )


class ExecutionWatcherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateExecutionInfo(self, request, context):
        """Update job info from a remote executor operator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExecutionWatcherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateExecutionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateExecutionInfo,
                    request_deserializer=tfx_dot_proto_dot_orchestration_dot_execution__watcher__pb2.UpdateExecutionInfoRequest.FromString,
                    response_serializer=tfx_dot_proto_dot_orchestration_dot_execution__watcher__pb2.UpdateExecutionInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tfx.orchestration.ExecutionWatcherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExecutionWatcherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateExecutionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tfx.orchestration.ExecutionWatcherService/UpdateExecutionInfo',
            tfx_dot_proto_dot_orchestration_dot_execution__watcher__pb2.UpdateExecutionInfoRequest.SerializeToString,
            tfx_dot_proto_dot_orchestration_dot_execution__watcher__pb2.UpdateExecutionInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
